name: Deploy to GitHub Pages

# Kapan workflow ini akan berjalan
on:
  # Memicu pada setiap push ke branch 'main' (atau 'master', sesuaikan dengan branch utama Anda)
  push:
    branches:
      - main
  # Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions
  workflow_dispatch:

# Izin khusus untuk GITHUB_TOKEN yang diperlukan untuk deployment GitHub Pages
permissions:
  contents: read  # Untuk checkout kode
  pages: write    # Untuk men-deploy ke Pages
  id-token: write # Untuk otentikasi dengan OIDC (diperlukan oleh actions/deploy-pages)

# Hanya izinkan satu deployment konkuren, lewati antrian di antara run yang sedang berjalan dan yang terbaru.
# Namun, JANGAN batalkan run yang sedang berjalan karena kita ingin deployment produksi ini selesai.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job untuk membangun situs Anda
  build:
    runs-on: ubuntu-latest # Menjalankan di server Linux terbaru yang disediakan GitHub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Mengambil kode dari repositori Anda

      # --- SESUAIKAN BAGIAN INI DENGAN PROSES BUILD ANDA ---
      # Jika situs Anda hanya HTML statis tanpa perlu build, Anda bisa melewati langkah build
      # Contoh jika menggunakan Node.js (misalnya React, Vue, Angular, dll.):
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18' # Ganti dengan versi Node.js yang Anda gunakan
      # - name: Install dependencies
      #   run: npm ci # atau 'npm install'
      # - name: Build project
      #   run: npm run build # atau perintah build Anda (misalnya 'ng build', 'yarn build')
      #
      # Jika menggunakan Jekyll (Ruby):
      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.0' # Ganti dengan versi Ruby Anda
      #     bundler-cache: true # Meng-cache gem untuk build lebih cepat
      # - name: Build with Jekyll
      #   run: bundle exec jekyll build --destination ./_site # Sesuaikan jika perlu
      # ---------------------------------------------------------

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5 # Mengkonfigurasi GitHub Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path ke folder yang berisi file-file situs Anda yang sudah di-build
          # Jika build menghasilkan folder 'dist', '_site', atau 'build':
          path: './dist' # Ganti dengan nama folder output build Anda (misal: './_site', './build', atau '.' jika file HTML ada di root)

  # Job untuk men-deploy situs ke GitHub Pages
  deploy:
    needs: build # Job 'deploy' ini baru akan berjalan setelah job 'build' selesai
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # URL situs yang di-deploy akan ditampilkan di log
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Action untuk men-deploy artefak ke GitHub Pages
